backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
local_backend: true
media_folder: 'assets/images/posts'
publish_mode: 'editorial_workflow'
locale: 'es'
collections:
  - name: 'blog'
    label: 'Post'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Autor', name: 'author', widget: 'hidden', default: 'Ilya' }
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Fecha', name: 'date', widget: 'datetime' }
      - { label: 'Tags', name: 'tags', widget: 'string' }
      - { label: 'Resumen', name: 'resum', widget: 'string' }
      - { label: 'Imagen Principal', name: 'image', widget: 'string' }
      - { label: 'Publicado', name: 'published', widget: 'boolean', default: false, required: false }
      - { label: 'Texto', name: 'body', widget: 'markdown' }
